image:
  name: python:3.8
  entrypoint: [""]

services:
  - docker:20.10.7-dind

variables:
  AWS_DEFAULT_REGION: us-east-1
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - deploy
  - test

test:
  stage: test
  script:
    - pip3 install awscli --upgrade
    - make setup_pip
    - pip3 install mlops-sm
    - python3 -m unittest
  needs:
    - job: build-package
      optional: true
  only:
    # TODO master
    - dev
    - pypi-ready

build-package:
  stage: deploy
  script:
    - pip3 install awscli --upgrade
    - aws codeartifact login --tool twine --repository pypi-store --domain ${CA_DOMAIN_NAME} --domain-owner ${CA_DOMAIN_OWNER}
    - pip3 install twine
    - make minor_version_up
    - cp .pypirc ~/.pypirc
    - python setup.py sdist
    - twine upload --repository='mlops-sm' dist/mlops_sm-* 
  when: manual
  only:
    # TODO master
    - dev
    - pypi-ready
