name: Test

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo & prepearing
      uses: actions/checkout@v1

    - name: Set up Python environment
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install pylint
      run: |
        pip install pylint pylint_junit

    - name: Run pylint
      run: |
        pylint --max-line-length=120 --max-args=8 --output-format=text,pylint_junit.JUnitReporter:lint_result.xml mlops_utilities/
      
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: always() # always run even if the previous step fails
      with:
        check_name: JUnit Lint Test Report
        report_paths: 'lint_result.xml'

  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo & prepearing
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: snok/install-poetry@v1
        with:
          version: 1.2.2
      - run: poetry install

      - name: Test with pytest
        run: |
          make test

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          check_name: JUnit Unit Test Report
          report_paths: 'report.xml'