name: Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repo & prepearing
        uses: actions/checkout@v3

      - name: Enforce timeout-minutes
        uses: komiya-atsushi/action-enforce-timeout-minutes@v1.0.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: snok/install-poetry@v1
        with:
          version: 1.2.2
      - run: poetry install

      - name: Test with pytest
        run: |
          make test

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: 'report.xml'